#' generateNetBenefitPlot
#'
#' Generate standardized net benefit plot for the given subgroup population.
#'
#' @param plpPrediction       The allValidationResults object generated by the generateSubgroupValidationData function.
#' @param subgroup            The name of the subgroup. For a binary subgroup, the name is followed by #1 or #0 to determine the subgroup.
#' @param outputFile          The output file path including the file name, such as plot/netbenefit_plot.pdf
#' @return                    It saves and returns the forest plot as a pdf file.
#' @export
generateNetBenefitPlot <- function(plpPrediction, subgroup, outputFile) {
  if(subgroup == "all") {
    true_labels <- plpPrediction$outcomeCount
    predicted_probs <- plpPrediction$value
  } else if(grepl("#", subgroup)){
    sv <- strsplit(subgroup, split = "#")
    s <- sv[[1]][1]
    v <- as.numeric(sv[[1]][2])
    if (s %in% colnames(plpPrediction) == F){
      stop("Invalid subgroup!")
    }
    true_labels <- plpPrediction$outcomeCount[plpPrediction[s] == v]
    predicted_probs <- plpPrediction$value[plpPrediction[s] == v]
  } else {
    stop("Invalid subgroup!")
  }

  roc_curve <- pROC::roc(true_labels, predicted_probs)
  prevalence <- sum(true_labels) / length(true_labels)
  nb <- roc_curve$sensitivities * prevalence - (1 - roc_curve$specificities) * (1 - prevalence) * (roc_curve$thresholds / (1 - roc_curve$thresholds))
  snb <- nb / prevalence

  nb_treat_all <- (prevalence - (1 - prevalence) * (roc_curve$thresholds / (1 - roc_curve$thresholds))) / prevalence
  #nb_treat_none <- rep(0, length(true_labels) + 1)
  nb_treat_none <- rep(0, length(nb_treat_all))

  df <- data.frame(Threshold = roc_curve$thresholds, NetBenefit = snb, TreatAll = nb_treat_all, TreatNone = nb_treat_none)
  df <- df[-c(1, nrow(df)), ]

  nb_plot <- ggplot2::ggplot(df, ggplot2::aes(x = Threshold)) +
    ggplot2::geom_line(ggplot2::aes(y = NetBenefit, color = "Model")) +
    ggplot2::geom_line(ggplot2::aes(y = TreatAll, color = "All")) +
    ggplot2::geom_line(ggplot2::aes(y = TreatNone, color = "None")) +
    ggplot2::coord_cartesian(
      xlim = c(0.0, 0.8),
      ylim = c(-0.2, 1)
    ) +
    ggplot2::scale_color_manual(
      name = "Decision Curve Analysis",
      values = c(Model = "black",
                 All = "brown",
                 None = "blue"
      ),
      labels = c(Model = "Model",
                 All = "Treat All",
                 None = "Treat None"
      ),
      breaks = c("Model",
                 "All",
                 "None"
      )
    ) +
    ggplot2::labs(
      x = "Threshold Probability",
      y = "Standardized Net Benefit"
    ) +
    ggplot2::theme(legend.position = c(0.76, 0.81),
              axis.title = ggplot2::element_text(size=19),
              text = ggplot2::element_text(size=17),
              legend.title=ggplot2::element_blank())

  plot(nb_plot)
  ggplot2::ggsave(outputFile, units="in", width=5, height=4, dpi=300)
  dev.off()
  return(nb_plot)
}
