#' generateForestPlot
#'
#' Generate forest plots based on AUROC and AUPRC values
#'
#' @param csvFile              If the subgroup validation table generated by the generateSubgroupValidationData function has been saved in a CSV file, it can be used as input here.
#' @param resultDataFrame      The subgroup validation table generated by the generateSubgroupValidationData function.
#' @param estimateCol          It can be set to AUROC or AUPRC to plot the forest diagram accordingly.
#' @param outputFile           The output file path including the file name, such as plot/AUPRC_forest_plot.tiff
#' @return                     It saves and returns the forest plot as a tiff file.
#' @export
generateForestPlot <- function(csvFile=NULL, resultDataFrame=NULL, estimateCol='AUROC', outputFile="AUPRC_forest_plot.tiff"){
  if (is.null(resultDataFrame) && !is.null(csvFile)){
    df <- read.csv(csvFile)
  } else {
    df <- resultDataFrame
  }
  if (estimateCol == 'AUROC'){
    names(df)[names(df) == 'AUROC'] <- 'est'
    names(df)[names(df) == 'AUROC_Low'] <- 'low'
    names(df)[names(df) == 'AUROC_High'] <- 'high'
  } else {
    names(df)[names(df) == 'AUPRC'] <- 'est'
    names(df)[names(df) == 'AUPRC_Low'] <- 'low'
    names(df)[names(df) == 'AUPRC_High'] <- 'high'
  }

  names(df)[names(df) == 'CohortCount'] <- 'N'
  names(df)[names(df) == 'Incidence'] <- 'O (%)'

  df <- df[c('Subgroup', 'N', 'O (%)', 'est', 'low', 'high')]

  df$Subgroup <- ifelse(is.na(df$est), df$Subgroup, paste0("   ", df$Subgroup, "    "))
  df$N <- ifelse(is.na(df$est), '', df$N)
  df$`O (%)` <- ifelse(is.na(df$est), '', df$`O (%)`)

  df$` ` <- paste(rep(" ", 20), collapse = " ")
  if (estimateCol == 'AUROC'){
    df$`AUROC (95% CI)` <- ifelse(is.na(df$est), "", sprintf("%.2f (%.2f to %.2f)",df$est, df$low, df$high))
  } else {
    df$`AUPRC (95% CI)` <- ifelse(is.na(df$est), "", sprintf("%.2f (%.2f to %.2f)",df$est, df$low, df$high))
  }

  tiff(outputFile, width=19, height=22, units="cm", res=300)
  p <- forestploter::forest(df[,c(1:3, 7:8)],
              est = df$est,
              lower = df$low,
              upper = df$high,
              ci_column = 4,
              ref_line = round(df$est[2], digits = 2),
              arrow_lab = c("Min", "Max"),
              xlim = c(round(min(df$low, na.rm = TRUE), digits = 2), round(max(df$high, na.rm = TRUE), digits = 2)),
              ticks_at = c(round(min(df$low, na.rm = TRUE), digits = 2),
                           round(mean(df$est, na.rm = TRUE), digits = 2),
                           round(max(df$high, na.rm = TRUE), digits = 2)),
              footnote = "")

  plot(p)
  dev.off()
}


#' generateMultiForestPlot
#'
#' Generate forest plots for AUROC and AUPRC values in a single plot
#'
#' @param csvFile              If the subgroup validation table generated by the generateSubgroupValidationData function has been saved in a CSV file, it can be used as input here.
#' @param resultDataFrame      The subgroup validation table generated by the generateSubgroupValidationData function.
#' @param outputFile           The output file path including the file name, such as plot/AUPRC_forest_plot.tiff
#' @return                     It saves and returns the forest plot as a tiff file.
#' @export
generateMultiForestPlot <- function(csvFile=NULL, resultDataFrame=NULL, outputFile="AUPRC_forest_plot.tiff"){
  if (is.null(resultDataFrame) && !is.null(csvFile)){
    df <- read.csv(csvFile)
  } else {
    df <- resultDataFrame
  }

  names(df)[names(df) == 'CohortCount'] <- 'N'
  names(df)[names(df) == 'Incidence'] <- 'O (%)'

  df <- df[c('Subgroup', 'N', 'O (%)', 'AUROC', 'AUROC_Low', 'AUROC_High', 'AUPRC', 'AUPRC_Low', 'AUPRC_High')]

  df$Subgroup <- ifelse(is.na(df$AUROC), df$Subgroup, paste0("   ", df$Subgroup, "    "))
  df$N <- ifelse(is.na(df$AUROC), '', df$N)
  df$`O (%)` <- ifelse(is.na(df$AUROC), '', df$`O (%)`)

  df$` ` <- paste(rep(" ", 20), collapse = " ")
  df$`AUROC (95% CI)` <- ifelse(is.na(df$AUROC), "", sprintf("%.2f (%.2f to %.2f)",df$AUROC, df$AUROC_Low, df$AUROC_High))

  df$`  ` <- paste(rep(" ", 20), collapse = " ")
  df$`AUPRC (95% CI)` <- ifelse(is.na(df$AUPRC), "", sprintf("%.2f (%.2f to %.2f)",df$AUPRC, df$AUPRC_Low, df$AUPRC_High))

  df <- df[c('Subgroup', 'N', 'O (%)', 'AUROC', 'AUROC_Low', 'AUROC_High', ' ', 'AUROC (95% CI)', 'AUPRC', 'AUPRC_Low', 'AUPRC_High', '  ', 'AUPRC (95% CI)')]

  tiff(outputFile, width=27, height=22, units="cm", res=300)
  p <- forestploter::forest(df[, c(1:3, 7:8, 12:13)],
              est = list(df$AUROC, df$AUPRC),
              lower = list(df$AUROC_Low, df$AUPRC_Low),
              upper = list(df$AUROC_High, df$AUPRC_High),
              ci_column = c(4, 6),
              ref_line = c(round(df$AUROC[2], digits = 2), round(df$AUPRC[2], digits = 2)),
              arrow_lab = list(c("Min", "Max"), c("Min", "Max")),
              xlim = list(c(round(min(df$AUROC_Low, na.rm = TRUE), digits = 2), round(max(df$AUROC_High, na.rm = TRUE), digits = 2)),
                          c(round(min(df$AUPRC_Low, na.rm = TRUE), digits = 2), round(max(df$AUPRC_High, na.rm = TRUE), digits = 2))
              ),
              ticks_at = list(
                c(round(min(df$AUROC_Low, na.rm = TRUE), digits = 2),
                  round(mean(df$AUROC, na.rm = TRUE), digits = 2),
                  round(max(df$AUROC_High, na.rm = TRUE), digits = 2)),

                c(round(min(df$AUPRC_Low, na.rm = TRUE), digits = 2),
                  round(mean(df$AUPRC, na.rm = TRUE), digits = 2),
                  round(max(df$AUPRC_High, na.rm = TRUE), digits = 2))
              )
  )
  plot(p)
  dev.off()
}
